### ISSUE TITLE
有关 FemtoDetMixUp 的一个问题

### ISSUE THREAD

**Issue by ZS-YANG** [yh-pengtu/FemtoDet#17]
对比FemtoDetMixUp 方法与MixUp方法，发现FemtoDetMixUp 中增加了下面的额外数据处理，请问这个处理是要解决什么问题呢
https://github.com/yh-pengtu/FemtoDet/blob/15e91c59e8616c9735d84afbdb8d89282eb187b0/mmdet/datasets/pipelines/transforms.py#L2834-2844
```
retrieve_results = results['mix_results'][0]
retrieve_img = retrieve_results['img']
img_temp = np.zeros_like(retrieve_img)
for box in retrieve_results['gt_bboxes']:
    box = [int(x) for x in box]
    x1, y1, x2, y2 = box[:]
    img_temp[y1:y2, x1:x2, :] = retrieve_img[y1:y2, x1:x2, :]

**Comment by yh-pengtu** [comment]
Complex mixed cases must focus on meaningful object patches, while FemtoDet is too light to tackle background information.

**Comment by ZS-YANG** [comment]
thx.
