### ISSUE TITLE
Results (trained on VOC) and Models

### ISSUE THREAD

**Issue by ZS-YANG** [yh-pengtu/FemtoDet#18]
Results (trained on VOC) and Models中的百度网盘链接过期了，麻烦作者再更新一下吧

**Comment by xiaolaji986** [comment]
Results (trained on VOC) and Models中的百度网盘链接过期了，麻烦作者再更新一下吧

**Comment by yh-pengtu** [comment]
The links have been updated; good luck!

**Comment by ZS-YANG** [comment]
thx.
