### ISSUE TITLE
Thanks for this work

### ISSUE THREAD

**Issue by ZS-YANG** [yh-pengtu/FemtoDet#3]
When to publish the code，thanks

**Comment by ZS-YANG** [comment]
thanks,  baby ♥♥♥

**Comment by yh-pengtu** [comment]
Because I departed from my previous company, I need some time to rewrite and reproduce the code of FemtoDet, but I assure you I will put in my utmost effort to complete this task. I aim to provide the relevant results to you by the end of this month.

**Comment by yh-pengtu** [comment]
Thanks for u kind attention, my little cutie!!!

**Comment by ZS-YANG** [comment]
my darling，you are so fast。bythe way, will you publish the trained weights used in the paper?😋

**Comment by yh-pengtu** [comment]
> my darling，you are so fast。bythe way, will you publish the trained weights used in the paper?😋

v 100, I will tell u more detail. 😋

**Comment by yh-pengtu** [comment]
> my darling，you are so fast。bythe way, will you publish the trained weights used in the paper?😋

Trained weights and logs on VOC will release after a few days.

**Comment by ZS-YANG** [comment]
thanks for reply.I'm having some trouble, when I try to package the environment the following error occurs：
```
(test) root@dsw-239189-5787647ff4-59sqz:/mnt/workspace# conda pack -n test
Collecting packages...
CondaPackError: Cannot pack an environment with editable packages
installed (e.g. from `python setup.py develop` or
 `pip install -e`). Editable packages found:

- /mnt/workspace/src/mmtrack
```
Can you provide other installation methods for 【mmtrack             0.14.0       /mnt/workspace/src/mmtrack 】, the original method in this project is 【pip install  -e git+https://github.com/open-mmlab/mmtracking#egg=mmtrack】

 Byt the way, there is an error at ‘FemtoDet-main/requirements/optional.txt’. Sklearn should be changed to scikit-learn

**Comment by yh-pengtu** [comment]
> thanks for reply.I'm having some trouble, when I try to package the environment the following error occurs：
> 
> ```
> (test) root@dsw-239189-5787647ff4-59sqz:/mnt/workspace# conda pack -n test
> Collecting packages...
> CondaPackError: Cannot pack an environment with editable packages
> installed (e.g. from `python setup.py develop` or
>  `pip install -e`). Editable packages found:
> 
> - /mnt/workspace/src/mmtrack
> ```
> 
> Can you provide other installation methods for 【mmtrack 0.14.0 /mnt/workspace/src/mmtrack 】, the original method in this project is 【pip install -e git+[https://github.com/open-mmlab/mmtracking#egg=mmtrack】](https://github.com/open-mmlab/mmtracking#egg=mmtrack%E3%80%91)
> 
> Byt the way, there is an error at ‘FemtoDet-main/requirements/optional.txt’. Sklearn should be changed to scikit-learn

Sorry, I have not used mmtrack, maybe this error was caused by version conflicts. And thanks for u fixed sklearn error!

**Comment by ZS-YANG** [comment]
hi, when I try to install the library with pip, I encounter some version conflicts. Can you provide the specific version information through "pip freeze > requirements.txt"
Command? 😭
